"""crear tablas de auth

Revision ID: 0767bfec6564
Revises: 
Create Date: 2026-09-21 16:17:02.265033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0767bfec6564'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('imagen_public_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'eliminado', 'reportado', 'suspendido', 'pendiente', name='estado_entidad'), server_default=sa.text("'pendiente'::estado_entidad"), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('updated_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('eliminado_en', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_table('history_password',
    sa.Column('id_history_password', sa.Integer(), nullable=False),
    sa.Column('password_hash_anterior', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['auth_users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_history_password')
    )
    op.create_index(op.f('ix_history_password_password_hash_anterior'), 'history_password', ['password_hash_anterior'], unique=False)
    op.create_table('recover_password',
    sa.Column('id_recover_password', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['auth_users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_recover_password')
    )
    op.create_index(op.f('ix_recover_password_token_hash'), 'recover_password', ['token_hash'], unique=True)
    op.create_table('sesiones',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('hash_refresh_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('inicio_sesion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['auth_users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_index(op.f('ix_sesiones_hash_refresh_token'), 'sesiones', ['hash_refresh_token'], unique=True)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['auth_users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_index(op.f('ix_sesiones_hash_refresh_token'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index(op.f('ix_recover_password_token_hash'), table_name='recover_password')
    op.drop_table('recover_password')
    op.drop_index(op.f('ix_history_password_password_hash_anterior'), table_name='history_password')
    op.drop_table('history_password')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
